export interface EmoteDefinition {
  command: string
  aliases?: string[]
  text: string
  targetText: string
}

export const EMOTES: readonly EmoteDefinition[] = [
  { command: 'agree', text: 'agrees.', targetText: 'agrees with {target}.' },
  { command: 'amaze', text: 'is amazed!', targetText: 'is amazed by {target}.' },
  { command: 'angry', aliases: ['mad'], text: 'raises a fist in anger.', targetText: 'raises a fist in anger at {target}.' },
  { command: 'apologize', aliases: ['sorry'], text: 'apologizes to everyone. Sorry!', targetText: 'apologizes to {target}. Sorry!' },
  { command: 'applaud', aliases: ['bravo'], text: 'applauds. Bravo!', targetText: 'applauds at {target}. Bravo!' },
  { command: 'attacktarget', text: 'tells everyone to attack something.', targetText: 'tells everyone to attack {target}.' },
  { command: 'bark', text: 'barks. Woof woof!', targetText: 'barks at {target}.' },
  { command: 'bashful', text: 'is bashful.', targetText: "is so bashful...too bashful to get {target}'s attention." },
  { command: 'beckon', text: 'beckons everyone over.', targetText: 'beckons {target} over.' },
  { command: 'beg', text: 'begs everyone around. How pathetic.', targetText: 'begs {target}. How pathetic.' },
  { command: 'belch', aliases: ['burp'], text: 'lets out a loud belch.', targetText: "burps rudely in {target}'s face." },
  { command: 'bite', text: 'looks around for someone to bite.', targetText: 'bites {target}. Ouch!' },
  { command: 'bleed', text: 'bleeds.', targetText: 'bleeds.' },
  { command: 'blink', text: 'blinks.', targetText: 'blinks at {target}.' },
  { command: 'blow', aliases: ['kiss'], text: 'blows a kiss into the wind.', targetText: 'blows a kiss to {target}.' },
  { command: 'blush', text: 'blushes.', targetText: 'blushes at {target}.' },
  { command: 'boggle', text: 'boggles at the situation.', targetText: 'boggles at {target}.' },
  { command: 'bonk', aliases: ['doh'], text: 'bonks themself on the noggin. Doh!', targetText: 'bonks {target} on the noggin. Doh!' },
  { command: 'bored', text: 'is overcome with boredom. Oh the drudgery!', targetText: 'is terribly bored with {target}.' },
  { command: 'bounce', text: 'bounces up and down.', targetText: 'bounces up and down in front of {target}.' },
  { command: 'bow', text: 'bows down graciously.', targetText: 'bows before {target}.' },
  { command: 'brandish', text: 'brandishes a weapon fiercely.', targetText: 'brandishes a weapon fiercely at {target}.' },
  { command: 'brb', text: "lets everyone know they'll be right back.", targetText: "lets {target} know they'll be right back." },
  {
    command: 'bye', aliases: ['farewell', 'goodbye'],
    text: 'waves goodbye to everyone. Farewell!',
    targetText: 'waves goodbye to {target}. Farewell!',
  },
  { command: 'cackle', text: 'cackles maniacally at the situation.', targetText: 'cackles maniacally at {target}.' },
  { command: 'calm', text: 'remains calm.', targetText: 'tries to calm {target} down.' },
  { command: 'cat', aliases: ['scratch'], text: 'scratches themself. Ah, much better!', targetText: 'scratches {target}. How catty!' },
  { command: 'charge', text: 'starts to charge.', targetText: 'starts to charge.' },
  { command: 'cheer', aliases: ['woot'], text: 'cheers!', targetText: 'cheers at {target}.' },
  { command: 'chew', aliases: ['eat', 'feast'], text: 'begins to eat.', targetText: 'begins to eat in front of {target}.' },
  {
    command: 'chicken', aliases: ['flap', 'strut'],
    text: 'struts around with arms flapping. Cluck, Cluck, Chicken!',
    targetText: 'struts around {target} with arms flapping. Cluck, Cluck, Chicken!',
  },
  { command: 'chuckle', text: 'lets out a hearty chuckle.', targetText: 'chuckles at {target}.' },
  { command: 'clap', text: 'claps excitedly.', targetText: 'claps excitedly for {target}.' },
  { command: 'cold', text: 'lets everyone know they are cold.', targetText: 'lets {target} know they are cold.' },
  { command: 'comfort', text: 'needs to be comforted.', targetText: 'comforts {target}.' },
  { command: 'commend', text: 'commends everyone on a job well done.', targetText: 'commends {target} on a job well done.' },
  { command: 'confused', text: 'is hopelessly confused.', targetText: 'looks at {target} with a confused look.' },
  { command: 'congrats', text: 'congratulates everyone around.', targetText: 'congratulates {target}.' },
  { command: 'cough', text: 'lets out a hacking cough.', targetText: 'coughs at {target}.' },
  { command: 'cower', aliases: ['fear'], text: 'cowers in fear.', targetText: 'cowers in fear at the sight of {target}.' },
  {
    command: 'crack', aliases: ['knuckles'],
    text: 'cracks their knuckles.',
    targetText: 'cracks their knuckles while staring at {target}.',
  },
  { command: 'cringe', text: 'cringes in fear.', targetText: 'cringes away from {target}.' },
  { command: 'cry', aliases: ['sob', 'weep'], text: 'cries.', targetText: "cries on {target}'s shoulder." },
  { command: 'cuddle', aliases: ['spoon'], text: 'needs to be cuddled.', targetText: 'cuddles up against {target}.' },
  { command: 'curious', text: 'expresses curiosity to those around.', targetText: 'is curious what {target} is up to.' },
  { command: 'curtsey', text: 'curtseys.', targetText: 'curtseys before {target}.' },
  { command: 'dance', text: 'bursts into dance.', targetText: 'dances with {target}.' },
  { command: 'ding', text: 'has reached a new level. DING!', targetText: 'congratulates {target} on a new level. DING!' },
  {
    command: 'disappointed', aliases: ['frown'],
    text: 'frowns.',
    targetText: 'frowns with disappointment at {target}.',
  },
  {
    command: 'doom', aliases: ['threat', 'wrath'],
    text: 'threatens everyone with the wrath of doom.',
    targetText: 'threatens {target} with the wrath of doom.',
  },
  {
    command: 'drink', aliases: ['party', 'shindig'],
    text: 'raises a drink in the air before chugging it down. Cheers!',
    targetText: 'raises a drink to {target}. Cheers!',
  },
  { command: 'drool', text: 'drools.', targetText: 'looks at {target} and begins to drool.' },
  { command: 'duck', text: 'ducks for cover.', targetText: 'ducks behind {target}.' },
  { command: 'excited', aliases: ['talkex'], text: 'talks excitedly with everyone.', targetText: 'talks excitedly with {target}.' },
  { command: 'eye', text: 'crosses their eyes.', targetText: 'eyes {target} up and down.' },
  {
    command: 'facepalm',
    text: 'covers their face with their palm.',
    targetText: 'looks over at {target} and covers their face with their palm.',
  },
  { command: 'fart', text: 'farts loudly. Whew...what stinks?', targetText: 'brushes up against {target} and farts loudly.' },
  {
    command: 'fidget', aliases: ['impatient'],
    text: 'fidgets.',
    targetText: 'fidgets impatiently while waiting for {target}.',
  },
  { command: 'flee', text: 'yells for everyone to flee!', targetText: 'yells for {target} to flee!' },
  {
    command: 'flex', aliases: ['strong'],
    text: 'flexes their muscles. Oooooh so strong!',
    targetText: 'flexes at {target}. Oooooh so strong!',
  },
  { command: 'flirt', text: 'flirts.', targetText: 'flirts with {target}.' },
  { command: 'flop', text: 'flops about helplessly.', targetText: 'flops about helplessly around {target}.' },
  { command: 'followme', text: 'motions for everyone to follow.', targetText: 'motions for {target} to follow.' },
  { command: 'gasp', text: 'gasps.', targetText: 'gasps at {target}.' },
  { command: 'gaze', text: 'gazes off into the distance.', targetText: 'gazes longingly at {target}.' },
  { command: 'giggle', text: 'giggles.', targetText: 'giggles at {target}.' },
  { command: 'glad', aliases: ['happy', 'yay'], text: 'is filled with happiness!', targetText: 'is very happy with {target}!' },
  { command: 'glare', text: 'glares angrily.', targetText: 'glares angrily at {target}.' },
  { command: 'gloat', text: "gloats over everyone's misfortune.", targetText: "gloats over {target}'s misfortune." },
  { command: 'golfclap', text: 'claps half-heartedly, clearly unimpressed.', targetText: 'claps for {target}, clearly unimpressed.' },
  { command: 'greet', text: 'greets everyone warmly.', targetText: 'greets {target} warmly.' },
  { command: 'grin', aliases: ['wicked'], text: 'grins wickedly.', targetText: 'grins wickedly at {target}.' },
  { command: 'groan', text: 'begins to groan.', targetText: 'looks at {target} and groans.' },
  {
    command: 'grovel', aliases: ['peon'],
    text: 'grovels on the ground, wallowing in subservience.',
    targetText: 'grovels before {target} like a subservient peon.',
  },
  { command: 'growl', text: 'growls menacingly.', targetText: 'growls menacingly at {target}.' },
  { command: 'guffaw', text: 'lets out a boisterous guffaw!', targetText: 'takes one look at {target} and lets out a guffaw!' },
  { command: 'hail', text: 'hails those around.', targetText: 'hails {target}.' },
  { command: 'healme', text: 'calls out for healing!', targetText: 'calls out for healing!' },
  { command: 'hello', aliases: ['hi'], text: 'greets everyone with a hearty hello!', targetText: 'greets {target} with a hearty hello!' },
  { command: 'helpme', text: 'cries out for help!', targetText: 'cries out for help!' },
  { command: 'highfive', text: 'puts up a hand for a high five.', targetText: 'gives {target} a high five!' },
  { command: 'hug', text: 'needs a hug!', targetText: 'hugs {target}.' },
  { command: 'hungry', aliases: ['food', 'pizza'], text: 'is hungry!', targetText: 'is hungry. Maybe {target} has some food...' },
  { command: 'incoming', text: 'warns everyone of incoming enemies!', targetText: 'points out {target} as an incoming enemy!' },
  {
    command: 'insult',
    text: 'thinks everyone around is a son of a motherless ogre.',
    targetText: 'thinks {target} is the son of a motherless ogre.',
  },
  { command: 'introduce', text: 'introduces themself to everyone.', targetText: 'introduces themself to {target}.' },
  { command: 'jk', text: 'was just kidding!', targetText: 'lets {target} know they were just kidding!' },
  { command: 'kneel', text: 'kneels down.', targetText: 'kneels before {target}.' },
  { command: 'laugh', aliases: ['lol'], text: 'laughs.', targetText: 'laughs at {target}.' },
  { command: 'lavish', aliases: ['praise'], text: 'praises the Light.', targetText: 'lavishes praise upon {target}.' },
  { command: 'lay', aliases: ['lie'], text: 'lies down.', targetText: 'lies down before {target}.' },
  { command: 'lick', text: 'licks their lips.', targetText: 'licks {target}.' },
  { command: 'listen', text: 'is listening!', targetText: 'listens intently to {target}.' },
  { command: 'lost', text: 'is hopelessly lost.', targetText: 'wants {target} to know they are hopelessly lost.' },
  { command: 'love', text: 'feels the love.', targetText: 'loves {target}.' },
  { command: 'massage', text: 'needs a massage!', targetText: "massages {target}'s shoulders." },
  { command: 'moan', text: 'moans suggestively.', targetText: 'moans suggestively at {target}.' },
  { command: 'mock', text: 'mocks life and all it stands for.', targetText: 'mocks the foolishness of {target}.' },
  { command: 'moo', text: 'moos. Mooooooooooo.', targetText: 'moos at {target}. Mooooooooooo.' },
  { command: 'moon', text: 'drops their trousers and moons everyone.', targetText: 'drops their trousers and moons {target}.' },
  { command: 'mourn', text: 'mourns the loss of the dead.', targetText: 'mourns the death of {target}.' },
  { command: 'no', text: 'clearly states, NO.', targetText: 'tells {target} NO. Not going to happen.' },
  { command: 'nod', aliases: ['yes'], text: 'nods.', targetText: 'nods at {target}.' },
  { command: 'nosepick', aliases: ['pick'], text: 'picks their nose.', targetText: 'picks their nose and shows it to {target}.' },
  { command: 'oom', text: 'announces they have low mana!', targetText: 'announces they have low mana!' },
  { command: 'openfire', text: 'gives the order to open fire.', targetText: 'gives the order to open fire.' },
  { command: 'panic', text: 'runs around in a frenzied state of panic.', targetText: 'takes one look at {target} and panics.' },
  { command: 'pat', text: 'needs a pat.', targetText: 'gently pats {target}.' },
  { command: 'peer', text: 'peers around, searchingly.', targetText: 'peers at {target} searchingly.' },
  { command: 'pest', aliases: ['shoo'], text: 'shoos the measly pests away.', targetText: 'shoos {target} away. Be gone pest!' },
  { command: 'pity', text: 'pities those around.', targetText: 'looks down upon {target} with pity.' },
  { command: 'plead', text: 'drops to their knees and pleads in desperation.', targetText: 'pleads with {target}.' },
  { command: 'point', text: 'points over yonder.', targetText: 'points at {target}.' },
  { command: 'poke', text: 'pokes their belly and giggles.', targetText: 'pokes {target}. Hey!' },
  { command: 'ponder', text: 'ponders the situation.', targetText: "ponders {target}'s actions." },
  { command: 'pounce', text: 'pounces out from the shadows.', targetText: 'pounces on top of {target}.' },
  { command: 'pray', text: 'prays to the Gods.', targetText: 'says a prayer for {target}.' },
  { command: 'purr', text: 'purrs like a kitten.', targetText: 'purrs at {target}.' },
  { command: 'puzzled', text: "is puzzled. What's going on here?", targetText: 'is puzzled by {target}.' },
  { command: 'question', aliases: ['talkq'], text: 'wants to know the meaning of life.', targetText: 'questions {target}.' },
  { command: 'raise', aliases: ['volunteer'], text: 'raises a hand in the air.', targetText: 'looks at {target} and raises a hand.' },
  { command: 'rasp', aliases: ['rude'], text: 'makes a rude gesture.', targetText: 'makes a rude gesture at {target}.' },
  { command: 'ready', aliases: ['rdy'], text: 'lets everyone know they are ready!', targetText: 'lets {target} know they are ready!' },
  { command: 'rear', aliases: ['shake'], text: 'shakes their rear.', targetText: 'shakes their rear at {target}.' },
  { command: 'regret', text: 'is filled with regret.', targetText: 'thinks that {target} will regret it.' },
  { command: 'roar', text: 'roars with bestial vigor. So fierce!', targetText: 'roars with bestial vigor at {target}. So fierce!' },
  { command: 'rofl', text: 'rolls on the floor laughing.', targetText: 'rolls on the floor laughing at {target}.' },
  { command: 'rolleyes', text: 'rolls their eyes.', targetText: 'rolls their eyes at {target}.' },
  { command: 'sad', text: 'hangs their head dejectedly.', targetText: 'hangs their head dejectedly.' },
  { command: 'salute', text: 'stands at attention and salutes.', targetText: 'salutes {target} with respect.' },
  { command: 'scared', text: 'is scared!', targetText: 'is scared of {target}.' },
  { command: 'sexy', text: 'is too sexy for their tunic...so sexy it hurts.', targetText: 'thinks {target} is a sexy devil.' },
  { command: 'shimmy', text: 'shimmies before the masses.', targetText: 'shimmies before {target}.' },
  { command: 'shiver', text: 'shivers in their boots. Chilling!', targetText: 'shivers beside {target}. Chilling!' },
  { command: 'shrug', text: 'shrugs. Who knows?', targetText: 'shrugs at {target}. Who knows?' },
  { command: 'shy', text: 'smiles shyly.', targetText: 'smiles shyly at {target}.' },
  { command: 'sigh', text: 'lets out a long, drawn-out sigh.', targetText: 'sighs at {target}.' },
  { command: 'silly', text: 'tells a joke.', targetText: 'tells {target} a joke.' },
  { command: 'slap', text: 'slaps themself across the face. Ouch!', targetText: 'slaps {target} across the face. Ouch!' },
  { command: 'sleep', text: 'falls asleep. Zzzzzzz.', targetText: 'falls asleep. Zzzzzzz.' },
  { command: 'smell', aliases: ['stink'], text: 'smells the air around. Wow, someone stinks!', targetText: 'smells {target}. Wow, someone stinks!' },
  { command: 'smile', text: 'smiles.', targetText: 'smiles at {target}.' },
  { command: 'smirk', text: 'smirks slyly.', targetText: 'smirks slyly at {target}.' },
  { command: 'snarl', text: 'bares their teeth and snarls.', targetText: 'bares their teeth and snarls at {target}.' },
  { command: 'sneeze', text: 'sneezes. Achoo!', targetText: 'sneezes on {target}.' },
  { command: 'snicker', text: 'quietly snickers.', targetText: 'snickers at {target}.' },
  { command: 'sniff', text: 'sniffs the air.', targetText: 'sniffs {target}.' },
  { command: 'snub', text: 'snubs all of the lowly peons around.', targetText: 'snubs {target}.' },
  { command: 'soothe', text: 'needs to be soothed.', targetText: 'soothes {target}. There, there...things will be ok.' },
  { command: 'spit', text: 'spits on the ground.', targetText: 'spits on {target}.' },
  { command: 'stare', text: 'stares off into the distance.', targetText: 'stares {target} down.' },
  { command: 'surprised', text: 'is so surprised!', targetText: "is surprised by {target}'s actions." },
  {
    command: 'surrender',
    text: 'surrenders to the opponents.',
    targetText: 'surrenders before {target}. Such is the agony of defeat...',
  },
  { command: 'talk', text: 'talks to themself since no one else seems interested.', targetText: 'wants to talk things over with {target}.' },
  { command: 'tap', text: 'taps a foot. Hurry up already!', targetText: 'taps a foot while waiting for {target}.' },
  { command: 'taunt', text: 'taunts everyone around. Bring it fools!', targetText: 'makes a taunting gesture at {target}. Bring it!' },
  { command: 'tease', text: 'is such a tease.', targetText: 'teases {target}.' },
  { command: 'thank', aliases: ['ty'], text: 'thanks everyone around.', targetText: 'thanks {target}.' },
  { command: 'think', text: 'is lost in thought.', targetText: 'thinks about {target}.' },
  { command: 'thirsty', text: 'is so thirsty. Can anyone spare a drink?', targetText: 'lets {target} know they are thirsty. Spare a drink?' },
  { command: 'tickle', text: 'wants to be tickled. Hee hee!', targetText: 'tickles {target}. Hee hee!' },
  { command: 'tired', text: 'lets everyone know they are tired.', targetText: 'lets {target} know they are tired.' },
  { command: 'train', text: 'makes train noises. Choo choo!', targetText: 'makes train noises. Choo choo!' },
  { command: 'veto', text: 'vetoes the motion on the floor.', targetText: "vetoes {target}'s motion." },
  { command: 'victory', text: 'basks in the glory of victory.', targetText: 'basks in the glory of victory with {target}.' },
  { command: 'violin', text: "begins to play the world's smallest violin.", targetText: "plays the world's smallest violin for {target}." },
  { command: 'wait', text: 'asks everyone to wait.', targetText: 'asks {target} to wait.' },
  { command: 'wave', text: 'waves.', targetText: 'waves at {target}.' },
  { command: 'welcome', text: 'welcomes everyone.', targetText: 'welcomes {target}.' },
  { command: 'whine', text: 'whines pathetically.', targetText: 'whines pathetically at {target}.' },
  { command: 'whistle', text: 'lets forth a sharp whistle.', targetText: 'whistles at {target}.' },
  { command: 'whoa', text: 'is blown away.', targetText: 'is blown away by {target}.' },
  { command: 'wink', text: 'winks slyly.', targetText: 'winks slyly at {target}.' },
  { command: 'work', text: 'begins to work.', targetText: 'works with {target}.' },
  { command: 'yawn', text: 'yawns sleepily.', targetText: 'yawns sleepily at {target}.' },
  { command: 'yw', text: 'was happy to help.', targetText: 'was happy to help {target}.' },
]
